### ISSUE TITLE
Crash when parsing PE with huge number of exception entries

### ISSUE THREAD

**Issue by Eran-YT** [jnastarot/enma_pe#3]
Hey,
When parsing a PE with a huge number of exception entries, enma_pe crashes in handle_unwind_info (pe_exceptions.cpp)
The problem is that in line 302
`auto& unwind_entry = exceptions.get_unwind_entries()[exceptions.get_unwind_entries().size() - 1];`
A reference in used, and then the function is called recursively, and the vector `exceptions` is reallocated, and so the reference is now invalid, but is used later.

**Comment by jnastarot** [comment]
did fix it in last commit https://github.com/jnastarot/enma_pe/commit/1fc9d3a59bf0066eaed1d04341e6637f632d8202
