### ISSUE TITLE
get_export_directory is very slow

### ISSUE THREAD

**Issue by Eran-YT** [jnastarot/enma_pe#4]
get_export_directory is O(n^2), but most of the work is redundant, as it constantly reparses the export name array, when it could be parsed once, put into a map (or unordered_map) and then just retrieve the name by ordinal.
This would at most be O(n*log(n)) and is much faster.

**Comment by jnastarot** [comment]
did also fix it https://github.com/jnastarot/enma_pe/commit/c59c667a6cca3d25637e7eda3c90cce369082e58
